"""
Seed data: ~250 songs + ~200 movies across Telugu, Hindi, English, Tamil.
Telugu-heavy distribution with auto language prioritization.
Expanded v2: more diversity across moods and languages.
"""
import os, sys, urllib.parse
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from database.db_utils import get_connection, init_db

def _yt(q): return f"https://www.youtube.com/results?search_query={urllib.parse.quote_plus(q)}"

SONGS = [
    ("Butta Bomma", "Armaan Malik", "Pop", "happy", "Telugu", 8.9, 9, _yt("Butta Bomma Armaan Malik official audio")),
    ("Ramuloo Ramulaa", "Anurag Kulkarni", "Folk Pop", "happy", "Telugu", 8.7, 9, _yt("Ramuloo Ramulaa Anurag Kulkarni official audio")),
    ("Saami Saami", "Mounika Yadav", "Folk", "happy", "Telugu", 8.6, 9, _yt("Saami Saami Mounika Yadav official audio")),
    ("Srivalli", "Sid Sriram", "Melody", "happy", "Telugu", 9.0, 10, _yt("Srivalli Sid Sriram official audio")),
    ("Oo Antava", "Indravathi Chauhan", "Dance", "happy", "Telugu", 8.5, 9, _yt("Oo Antava Indravathi Chauhan official audio")),
    ("Ramulo Ramula", "Anurag Kulkarni", "Mass", "happy", "Telugu", 8.4, 8, _yt("Ramulo Ramula Anurag Kulkarni official audio")),
    ("Top Lesi Poddi", "Arun Chiluveru", "Dance", "happy", "Telugu", 8.2, 8, _yt("Top Lesi Poddi Arun Chiluveru official audio")),
    ("Ranga Ranga", "Rahul Sipligunj", "Folk", "happy", "Telugu", 8.3, 8, _yt("Ranga Ranga Rahul Sipligunj official audio")),
    ("Jala Jala Jalapaatam", "Rahul Sipligunj", "Folk", "happy", "Telugu", 8.0, 7, _yt("Jala Jala Jalapaatam Rahul Sipligunj official audio")),
    ("Penny", "Rahul Sipligunj", "Dance", "happy", "Telugu", 7.8, 7, _yt("Penny Rahul Sipligunj official audio")),
    ("Mind Block", "Blaaze", "Dance", "happy", "Telugu", 8.1, 8, _yt("Mind Block Blaaze official audio")),
    ("Bullet", "Shweta Mohan", "Pop", "happy", "Telugu", 7.9, 7, _yt("Bullet Shweta Mohan official audio")),
    ("Nuvvu Naaku Nachav Title", "S.P. Balu", "Melody", "happy", "Telugu", 8.5, 8, _yt("Nuvvu Naaku Nachav Title S.P. Balu official audio")),
    ("Edo Edo", "Anurag Kulkarni", "Melody", "happy", "Telugu", 8.0, 7, _yt("Edo Edo Anurag Kulkarni official audio")),
    ("Choregraphed", "DSP", "Dance", "happy", "Telugu", 7.7, 7, _yt("Choregraphed DSP official audio")),
    ("Happy", "Pharrell Williams", "Pop", "happy", "English", 8.5, 10, _yt("Happy Pharrell Williams official audio")),
    ("Uptown Funk", "Bruno Mars", "Funk", "happy", "English", 9.0, 10, _yt("Uptown Funk Bruno Mars official audio")),
    ("Shake It Off", "Taylor Swift", "Pop", "happy", "English", 8.4, 9, _yt("Shake It Off Taylor Swift official audio")),
    ("Good as Hell", "Lizzo", "Pop", "happy", "English", 8.0, 8, _yt("Good as Hell Lizzo official audio")),
    ("Walking on Sunshine", "Katrina & The Waves", "Pop", "happy", "English", 8.1, 8, _yt("Walking on Sunshine Katrina & The Waves official audio")),
    ("Best Day of My Life", "American Authors", "Indie", "happy", "English", 7.8, 7, _yt("Best Day of My Life American Authors official audio")),
    ("Don't Stop Me Now", "Queen", "Rock", "happy", "English", 9.2, 10, _yt("Don't Stop Me Now Queen official audio")),
    ("Here Comes the Sun", "The Beatles", "Rock", "happy", "English", 9.0, 9, _yt("Here Comes the Sun The Beatles official audio")),
    ("Badtameez Dil", "Benny Dayal", "Bollywood", "happy", "Hindi", 8.3, 9, _yt("Badtameez Dil Benny Dayal official audio")),
    ("London Thumakda", "Labh Janjua", "Bollywood", "happy", "Hindi", 8.5, 9, _yt("London Thumakda Labh Janjua official audio")),
    ("Gallan Goodiyaan", "Shankar Mahadevan", "Bollywood", "happy", "Hindi", 8.0, 8, _yt("Gallan Goodiyaan Shankar Mahadevan official audio")),
    ("Balam Pichkari", "Vishal Dadlani", "Bollywood", "happy", "Hindi", 8.4, 9, _yt("Balam Pichkari Vishal Dadlani official audio")),
    ("Kar Gayi Chull", "Badshah", "Pop", "happy", "Hindi", 8.1, 8, _yt("Kar Gayi Chull Badshah official audio")),
    ("Cutiepie", "Pardeep Sran", "Pop", "happy", "Hindi", 7.5, 7, _yt("Cutiepie Pardeep Sran official audio")),
    ("Vaathi Coming", "Anirudh", "Mass", "happy", "Tamil", 8.8, 9, _yt("Vaathi Coming Anirudh official audio")),
    ("Enjoy Enjaami", "Dhee", "Folk", "happy", "Tamil", 8.5, 9, _yt("Enjoy Enjaami Dhee official audio")),
    ("Kutti Story", "Anirudh", "Pop", "happy", "Tamil", 8.3, 8, _yt("Kutti Story Anirudh official audio")),
    ("Jolly O Gymkhana", "Anirudh", "Dance", "happy", "Tamil", 8.0, 7, _yt("Jolly O Gymkhana Anirudh official audio")),
    ("Ye Maaya Chesave", "AR Rahman", "Melody", "sad", "Telugu", 9.0, 9, _yt("Ye Maaya Chesave AR Rahman official audio")),
    ("Nee Jathaga", "Karthik", "Melody", "sad", "Telugu", 8.8, 8, _yt("Nee Jathaga Karthik official audio")),
    ("Nuvvunte Naa Jathaga", "Haricharan", "Melody", "sad", "Telugu", 8.5, 8, _yt("Nuvvunte Naa Jathaga Haricharan official audio")),
    ("Kanulu Navainaa", "Anurag Kulkarni", "Melody", "sad", "Telugu", 8.3, 7, _yt("Kanulu Navainaa Anurag Kulkarni official audio")),
    ("Emitemito", "Sid Sriram", "Melody", "sad", "Telugu", 8.7, 8, _yt("Emitemito Sid Sriram official audio")),
    ("Oopiri Aaguthunnadhe", "Sid Sriram", "Melody", "sad", "Telugu", 8.4, 8, _yt("Oopiri Aaguthunnadhe Sid Sriram official audio")),
    ("Nee Kannu Neeli Samudram", "Sid Sriram", "Melody", "sad", "Telugu", 8.9, 9, _yt("Nee Kannu Neeli Samudram Sid Sriram official audio")),
    ("Maate Vinadhuga", "Sid Sriram", "Melody", "sad", "Telugu", 8.6, 8, _yt("Maate Vinadhuga Sid Sriram official audio")),
    ("Inkem Inkem", "Sid Sriram", "Melody", "sad", "Telugu", 9.1, 10, _yt("Inkem Inkem Sid Sriram official audio")),
    ("Ninnu Kori Title", "Sid Sriram", "Melody", "sad", "Telugu", 8.5, 8, _yt("Ninnu Kori Title Sid Sriram official audio")),
    ("Emai Poyave", "Sid Sriram", "Melody", "sad", "Telugu", 8.8, 9, _yt("Emai Poyave Sid Sriram official audio")),
    ("Yevadu Title", "Haricharan", "Sad", "sad", "Telugu", 7.8, 7, _yt("Yevadu Title Haricharan official audio")),
    ("Someone Like You", "Adele", "Pop", "sad", "English", 9.0, 10, _yt("Someone Like You Adele official audio")),
    ("Fix You", "Coldplay", "Rock", "sad", "English", 9.2, 10, _yt("Fix You Coldplay official audio")),
    ("Let Her Go", "Passenger", "Folk", "sad", "English", 8.7, 9, _yt("Let Her Go Passenger official audio")),
    ("Say Something", "Great Big World", "Pop", "sad", "English", 8.5, 8, _yt("Say Something Great Big World official audio")),
    ("The Night We Met", "Lord Huron", "Indie", "sad", "English", 8.6, 8, _yt("The Night We Met Lord Huron official audio")),
    ("Channa Mereya", "Arijit Singh", "Bollywood", "sad", "Hindi", 9.0, 10, _yt("Channa Mereya Arijit Singh official audio")),
    ("Tujhe Kitna Chahne Lage", "Arijit Singh", "Bollywood", "sad", "Hindi", 8.8, 9, _yt("Tujhe Kitna Chahne Lage Arijit Singh official audio")),
    ("Agar Tum Saath Ho", "Arijit Singh", "Bollywood", "sad", "Hindi", 9.1, 10, _yt("Agar Tum Saath Ho Arijit Singh official audio")),
    ("Tum Hi Ho", "Arijit Singh", "Bollywood", "sad", "Hindi", 9.2, 10, _yt("Tum Hi Ho Arijit Singh official audio")),
    ("Phir Bhi Tumko Chahunga", "Arijit Singh", "Bollywood", "sad", "Hindi", 8.5, 8, _yt("Phir Bhi Tumko Chahunga Arijit Singh official audio")),
    ("Ennai Noki Paayum Thota Title", "Darbuka Siva", "Melody", "sad", "Tamil", 8.3, 8, _yt("Ennai Noki Paayum Thota Title Darbuka Siva official audio")),
    ("Kannazhaga", "Dhanush", "Melody", "sad", "Tamil", 8.5, 8, _yt("Kannazhaga Dhanush official audio")),
    ("Nenjukkul Peidhidum", "Harris Jayaraj", "Melody", "sad", "Tamil", 8.7, 8, _yt("Nenjukkul Peidhidum Harris Jayaraj official audio")),
    ("Samajavaragamana", "Sid Sriram", "Melody", "romantic", "Telugu", 9.3, 10, _yt("Samajavaragamana Sid Sriram official audio")),
    ("Pillaa Raa", "Sid Sriram", "Melody", "romantic", "Telugu", 8.9, 9, _yt("Pillaa Raa Sid Sriram official audio")),
    ("Nee Kallalona", "Haricharan", "Melody", "romantic", "Telugu", 8.6, 8, _yt("Nee Kallalona Haricharan official audio")),
    ("Undiporaadhey", "Sid Sriram", "Melody", "romantic", "Telugu", 8.8, 9, _yt("Undiporaadhey Sid Sriram official audio")),
    ("Nee Paata Madhuram", "Sid Sriram", "Melody", "romantic", "Telugu", 8.5, 8, _yt("Nee Paata Madhuram Sid Sriram official audio")),
    ("Manasu Maree", "Sid Sriram", "Melody", "romantic", "Telugu", 8.7, 8, _yt("Manasu Maree Sid Sriram official audio")),
    ("Yem Maaya Chesavo", "AR Rahman", "Melody", "romantic", "Telugu", 8.9, 9, _yt("Yem Maaya Chesavo AR Rahman official audio")),
    ("Yennai Arindhaal Theme", "Harris Jayaraj", "Melody", "romantic", "Telugu", 8.0, 7, _yt("Yennai Arindhaal Theme Harris Jayaraj official audio")),
    ("Priya Priya", "SPB", "Melody", "romantic", "Telugu", 8.8, 8, _yt("Priya Priya SPB official audio")),
    ("Cheliya Cheliya", "SPB", "Classic", "romantic", "Telugu", 8.5, 8, _yt("Cheliya Cheliya SPB official audio")),
    ("Oka Praanam", "Shankar Mahadevan", "Melody", "romantic", "Telugu", 8.4, 8, _yt("Oka Praanam Shankar Mahadevan official audio")),
    ("Kanureppala Kaalam", "Sid Sriram", "Melody", "romantic", "Telugu", 8.6, 8, _yt("Kanureppala Kaalam Sid Sriram official audio")),
    ("Perfect", "Ed Sheeran", "Pop", "romantic", "English", 9.0, 10, _yt("Perfect Ed Sheeran official audio")),
    ("All of Me", "John Legend", "Pop", "romantic", "English", 9.1, 10, _yt("All of Me John Legend official audio")),
    ("Thinking Out Loud", "Ed Sheeran", "Pop", "romantic", "English", 8.8, 9, _yt("Thinking Out Loud Ed Sheeran official audio")),
    ("A Thousand Years", "Christina Perri", "Pop", "romantic", "English", 8.7, 9, _yt("A Thousand Years Christina Perri official audio")),
    ("Love Story", "Taylor Swift", "Pop", "romantic", "English", 8.5, 8, _yt("Love Story Taylor Swift official audio")),
    ("Tum Se Hi", "Mohit Chauhan", "Bollywood", "romantic", "Hindi", 8.9, 9, _yt("Tum Se Hi Mohit Chauhan official audio")),
    ("Tujh Mein Rab Dikhta Hai", "Roop Kumar", "Bollywood", "romantic", "Hindi", 9.0, 10, _yt("Tujh Mein Rab Dikhta Hai Roop Kumar official audio")),
    ("Pehla Nasha", "Udit Narayan", "Bollywood", "romantic", "Hindi", 9.2, 10, _yt("Pehla Nasha Udit Narayan official audio")),
    ("Raabta Title", "Arijit Singh", "Bollywood", "romantic", "Hindi", 8.3, 8, _yt("Raabta Title Arijit Singh official audio")),
    ("Imaikkaa Nodigal Love", "Anirudh", "Melody", "romantic", "Tamil", 8.5, 8, _yt("Imaikkaa Nodigal Love Anirudh official audio")),
    ("Kannaana Kanney", "Sid Sriram", "Melody", "romantic", "Tamil", 8.8, 9, _yt("Kannaana Kanney Sid Sriram official audio")),
    ("Enna Sona", "Arijit Singh", "Melody", "romantic", "Tamil", 8.7, 8, _yt("Enna Sona Arijit Singh official audio")),
    ("Naatu Naatu", "Rahul Sipligunj", "Mass", "energetic", "Telugu", 9.5, 10, _yt("Naatu Naatu Rahul Sipligunj official audio")),
    ("Dham Dham", "Anurag Kulkarni", "Mass", "energetic", "Telugu", 8.3, 8, _yt("Dham Dham Anurag Kulkarni official audio")),
    ("Blockbuster", "Thaman", "Mass", "energetic", "Telugu", 8.0, 8, _yt("Blockbuster Thaman official audio")),
    ("Jai Balayya", "Thaman", "Mass", "energetic", "Telugu", 8.2, 8, _yt("Jai Balayya Thaman official audio")),
    ("Boss Party", "Thaman", "Mass", "energetic", "Telugu", 8.1, 8, _yt("Boss Party Thaman official audio")),
    ("Pakka Local", "DSP", "Mass", "energetic", "Telugu", 8.4, 8, _yt("Pakka Local DSP official audio")),
    ("Swing Zara", "DSP", "Dance", "energetic", "Telugu", 8.0, 7, _yt("Swing Zara DSP official audio")),
    ("Cinema Choopista", "DSP", "Mass", "energetic", "Telugu", 8.5, 8, _yt("Cinema Choopista DSP official audio")),
    ("Dhoom Machale", "Sunidhi Chauhan", "Bollywood", "energetic", "Telugu", 7.5, 7, _yt("Dhoom Machale Sunidhi Chauhan official audio")),
    ("Gudilo Badilo", "DSP", "Mass", "energetic", "Telugu", 8.0, 7, _yt("Gudilo Badilo DSP official audio")),
    ("Thunderstruck", "AC/DC", "Rock", "energetic", "English", 9.0, 10, _yt("Thunderstruck AC/DC official audio")),
    ("Eye of the Tiger", "Survivor", "Rock", "energetic", "English", 8.8, 9, _yt("Eye of the Tiger Survivor official audio")),
    ("Stronger", "Kanye West", "Hip Hop", "energetic", "English", 8.5, 8, _yt("Stronger Kanye West official audio")),
    ("Levels", "Avicii", "EDM", "energetic", "English", 8.7, 9, _yt("Levels Avicii official audio")),
    ("Titanium", "David Guetta", "EDM", "energetic", "English", 8.4, 8, _yt("Titanium David Guetta official audio")),
    ("Malhari", "Vishal Dadlani", "Bollywood", "energetic", "Hindi", 8.6, 9, _yt("Malhari Vishal Dadlani official audio")),
    ("Khalibali", "Shivam Pathak", "Bollywood", "energetic", "Hindi", 8.3, 8, _yt("Khalibali Shivam Pathak official audio")),
    ("Zinda", "Siddharth Mahadevan", "Bollywood", "energetic", "Hindi", 8.0, 7, _yt("Zinda Siddharth Mahadevan official audio")),
    ("Aalaporaan Tamizhan", "AR Rahman", "Mass", "energetic", "Tamil", 8.5, 8, _yt("Aalaporaan Tamizhan AR Rahman official audio")),
    ("Surviva", "Yogi B", "Mass", "energetic", "Tamil", 8.3, 8, _yt("Surviva Yogi B official audio")),
    ("Sittharala Sirapadu", "DSP", "Motivational", "motivational", "Telugu", 8.5, 8, _yt("Sittharala Sirapadu DSP official audio")),
    ("Jai Lava Kusa Title", "DSP", "Mass", "motivational", "Telugu", 8.2, 8, _yt("Jai Lava Kusa Title DSP official audio")),
    ("Dosti", "Yuvan", "Motivational", "motivational", "Telugu", 8.0, 7, _yt("Dosti Yuvan official audio")),
    ("Saahore Baahubali", "MM Keeravani", "Epic", "motivational", "Telugu", 8.8, 9, _yt("Saahore Baahubali MM Keeravani official audio")),
    ("Vandhaai Ayya", "AR Rahman", "Motivational", "motivational", "Telugu", 8.3, 8, _yt("Vandhaai Ayya AR Rahman official audio")),
    ("Dandalayya", "MM Keeravani", "Epic", "motivational", "Telugu", 9.0, 9, _yt("Dandalayya MM Keeravani official audio")),
    ("Aagadu Title", "Thaman", "Mass", "motivational", "Telugu", 8.0, 7, _yt("Aagadu Title Thaman official audio")),
    ("Eye of the Tiger", "Survivor", "Rock", "motivational", "English", 8.8, 9, _yt("Eye of the Tiger Survivor official audio")),
    ("Lose Yourself", "Eminem", "Hip Hop", "motivational", "English", 9.3, 10, _yt("Lose Yourself Eminem official audio")),
    ("Stronger", "Kelly Clarkson", "Pop", "motivational", "English", 8.5, 8, _yt("Stronger Kelly Clarkson official audio")),
    ("Hall of Fame", "The Script", "Rock", "motivational", "English", 8.4, 8, _yt("Hall of Fame The Script official audio")),
    ("Fight Song", "Rachel Platten", "Pop", "motivational", "English", 8.0, 7, _yt("Fight Song Rachel Platten official audio")),
    ("Chak De India", "Sukhwinder Singh", "Bollywood", "motivational", "Hindi", 8.7, 9, _yt("Chak De India Sukhwinder Singh official audio")),
    ("Kar Har Maidaan Fateh", "Sukhwinder", "Bollywood", "motivational", "Hindi", 8.5, 8, _yt("Kar Har Maidaan Fateh Sukhwinder official audio")),
    ("Ziddi Dil", "Vishal Dadlani", "Bollywood", "motivational", "Hindi", 8.2, 7, _yt("Ziddi Dil Vishal Dadlani official audio")),
    ("Verithanam", "AR Rahman", "Mass", "motivational", "Tamil", 8.6, 8, _yt("Verithanam AR Rahman official audio")),
    ("Aaromale", "AR Rahman", "Melody", "calm", "Telugu", 8.5, 8, _yt("Aaromale AR Rahman official audio")),
    ("Manasa", "AR Rahman", "Melody", "calm", "Telugu", 8.7, 8, _yt("Manasa AR Rahman official audio")),
    ("Yedo Yedo", "Karthik", "Soft", "calm", "Telugu", 8.0, 7, _yt("Yedo Yedo Karthik official audio")),
    ("Hey Pillagaada", "Arijit Singh", "Melody", "calm", "Telugu", 8.3, 7, _yt("Hey Pillagaada Arijit Singh official audio")),
    ("Okey Oka Lokam", "Sid Sriram", "Melody", "calm", "Telugu", 8.5, 8, _yt("Okey Oka Lokam Sid Sriram official audio")),
    ("Atu Nuvve", "Sid Sriram", "Melody", "calm", "Telugu", 8.4, 7, _yt("Atu Nuvve Sid Sriram official audio")),
    ("Ooriki Utharana", "Anurag Kulkarni", "Melody", "calm", "Telugu", 8.0, 7, _yt("Ooriki Utharana Anurag Kulkarni official audio")),
    ("River Flows In You", "Yiruma", "Instrumental", "calm", "English", 9.0, 9, _yt("River Flows In You Yiruma official audio")),
    ("Weightless", "Marconi Union", "Ambient", "calm", "English", 8.5, 8, _yt("Weightless Marconi Union official audio")),
    ("Clair de Lune", "Debussy", "Classical", "calm", "English", 9.2, 9, _yt("Clair de Lune Debussy official audio")),
    ("Photograph", "Ed Sheeran", "Pop", "calm", "English", 8.7, 9, _yt("Photograph Ed Sheeran official audio")),
    ("Tere Bina", "AR Rahman", "Bollywood", "calm", "Hindi", 8.5, 8, _yt("Tere Bina AR Rahman official audio")),
    ("Kabira", "Arijit Singh", "Sufi", "calm", "Hindi", 8.8, 9, _yt("Kabira Arijit Singh official audio")),
    ("Moh Moh Ke Dhaage", "Papon", "Bollywood", "calm", "Hindi", 8.3, 7, _yt("Moh Moh Ke Dhaage Papon official audio")),
    ("Vaan Varuvaan", "Sid Sriram", "Melody", "calm", "Tamil", 8.4, 7, _yt("Vaan Varuvaan Sid Sriram official audio")),
    ("Simha Title", "DSP", "Mass", "angry", "Telugu", 8.0, 7, _yt("Simha Title DSP official audio")),
    ("Veera Simha Reddy", "Thaman", "Mass", "angry", "Telugu", 8.2, 8, _yt("Veera Simha Reddy Thaman official audio")),
    ("Waltair Veerayya", "DSP", "Mass", "angry", "Telugu", 8.1, 7, _yt("Waltair Veerayya DSP official audio")),
    ("Bheemla Nayak Title", "Thaman", "Mass", "angry", "Telugu", 8.5, 9, _yt("Bheemla Nayak Title Thaman official audio")),
    ("Akhanda Title", "Thaman", "Mass", "angry", "Telugu", 8.3, 8, _yt("Akhanda Title Thaman official audio")),
    ("Pushpa Title", "DSP", "Mass", "angry", "Telugu", 8.4, 8, _yt("Pushpa Title DSP official audio")),
    ("Breaking the Habit", "Linkin Park", "Nu Metal", "angry", "English", 8.8, 9, _yt("Breaking the Habit Linkin Park official audio")),
    ("Numb", "Linkin Park", "Rock", "angry", "English", 9.0, 10, _yt("Numb Linkin Park official audio")),
    ("In the End", "Linkin Park", "Rock", "angry", "English", 9.1, 10, _yt("In the End Linkin Park official audio")),
    ("Smells Like Teen Spirit", "Nirvana", "Grunge", "angry", "English", 9.3, 10, _yt("Smells Like Teen Spirit Nirvana official audio")),
    ("Agneepath Title", "Ajay-Atul", "Bollywood", "angry", "Hindi", 8.0, 7, _yt("Agneepath Title Ajay-Atul official audio")),
    ("Ala Vaikunthapurramuloo Title", "Thaman", "Mass", "angry", "Hindi", 8.0, 7, _yt("Ala Vaikunthapurramuloo Title Thaman official audio")),
    ("Vikram Title", "Anirudh", "Mass", "angry", "Tamil", 8.6, 9, _yt("Vikram Title Anirudh official audio")),
    ("Emo Emo", "Sid Sriram", "Melody", "neutral", "Telugu", 8.0, 7, _yt("Emo Emo Sid Sriram official audio")),
    ("Adiga Adiga", "Sid Sriram", "Indie", "neutral", "Telugu", 8.2, 7, _yt("Adiga Adiga Sid Sriram official audio")),
    ("Vennela", "Gowtham Bharadwaj", "Indie", "neutral", "Telugu", 7.8, 6, _yt("Vennela Gowtham Bharadwaj official audio")),
    ("Yedo Yedo", "Unni Menon", "Soft", "neutral", "Telugu", 7.9, 6, _yt("Yedo Yedo Unni Menon official audio")),
    ("Mundhinam", "Harris Jayaraj", "Melody", "neutral", "Telugu", 8.0, 7, _yt("Mundhinam Harris Jayaraj official audio")),
    ("Come Away With Me", "Norah Jones", "Jazz", "neutral", "English", 8.5, 8, _yt("Come Away With Me Norah Jones official audio")),
    ("Banana Pancakes", "Jack Johnson", "Acoustic", "neutral", "English", 8.0, 7, _yt("Banana Pancakes Jack Johnson official audio")),
    ("Sunday Morning", "Maroon 5", "Pop", "neutral", "English", 8.2, 7, _yt("Sunday Morning Maroon 5 official audio")),
    ("Ilahi", "Arijit Singh", "Bollywood", "neutral", "Hindi", 8.0, 7, _yt("Ilahi Arijit Singh official audio")),
    ("Iktara", "Amit Trivedi", "Bollywood", "neutral", "Hindi", 8.5, 8, _yt("Iktara Amit Trivedi official audio")),
    ("Nenjukkul", "Harris Jayaraj", "Melody", "neutral", "Tamil", 8.0, 7, _yt("Nenjukkul Harris Jayaraj official audio")),
    ("Komuram Bheemudo", "Kaala Bhairava", "Folk", "stressed", "Telugu", 8.7, 9, _yt("Komuram Bheemudo Kaala Bhairava official audio")),
    ("Dheevara", "Ramya Behara", "Epic", "stressed", "Telugu", 8.5, 8, _yt("Dheevara Ramya Behara official audio")),
    ("Antha Istam", "Sid Sriram", "Melody", "stressed", "Telugu", 7.8, 7, _yt("Antha Istam Sid Sriram official audio")),
    ("Let It Be", "The Beatles", "Rock", "stressed", "English", 9.0, 10, _yt("Let It Be The Beatles official audio")),
    ("Everybody Hurts", "R.E.M.", "Rock", "stressed", "English", 8.5, 8, _yt("Everybody Hurts R.E.M. official audio")),
    ("Unwell", "Matchbox Twenty", "Rock", "stressed", "English", 7.8, 7, _yt("Unwell Matchbox Twenty official audio")),
    ("Breathe Me", "Sia", "Pop", "stressed", "English", 8.3, 8, _yt("Breathe Me Sia official audio")),
    ("Kun Faya Kun", "AR Rahman", "Sufi", "stressed", "Hindi", 9.2, 10, _yt("Kun Faya Kun AR Rahman official audio")),
    ("Mann Bharrya", "B Praak", "Bollywood", "stressed", "Hindi", 8.0, 7, _yt("Mann Bharrya B Praak official audio")),
    ("Nee Parvu", "Sid Sriram", "Melody", "stressed", "Tamil", 8.0, 7, _yt("Nee Parvu Sid Sriram official audio")),
    ("Jigelu Rani", "Rahul Sipligunj", "Dance", "excited", "Telugu", 8.3, 8, _yt("Jigelu Rani Rahul Sipligunj official audio")),
    ("Rangamma Mangamma", "MM Manasi", "Folk", "excited", "Telugu", 8.5, 8, _yt("Rangamma Mangamma MM Manasi official audio")),
    ("Ra Ra Rakkamma", "DSP", "Dance", "excited", "Telugu", 7.8, 7, _yt("Ra Ra Rakkamma DSP official audio")),
    ("What What", "DSP", "Dance", "excited", "Telugu", 8.0, 7, _yt("What What DSP official audio")),
    ("Oo Baava", "Sid Sriram", "Dance", "excited", "Telugu", 7.9, 7, _yt("Oo Baava Sid Sriram official audio")),
    ("Dhimak Kharab", "Anurag Kulkarni", "Mass", "excited", "Telugu", 8.2, 8, _yt("Dhimak Kharab Anurag Kulkarni official audio")),
    ("Bawaal", "MJ5", "Youth", "excited", "Telugu", 7.5, 6, _yt("Bawaal MJ5 official audio")),
    ("Uptown Funk", "Bruno Mars", "Funk", "excited", "English", 9.0, 10, _yt("Uptown Funk Bruno Mars official audio")),
    ("Can't Hold Us", "Macklemore", "Hip Hop", "excited", "English", 8.5, 8, _yt("Can't Hold Us Macklemore official audio")),
    ("Party Rock Anthem", "LMFAO", "EDM", "excited", "English", 8.3, 8, _yt("Party Rock Anthem LMFAO official audio")),
    ("Nashe Si Chadh Gayi", "Arijit Singh", "Bollywood", "excited", "Hindi", 8.5, 8, _yt("Nashe Si Chadh Gayi Arijit Singh official audio")),
    ("Abhi Toh Party", "Badshah", "Bollywood", "excited", "Hindi", 8.0, 7, _yt("Abhi Toh Party Badshah official audio")),
    ("Rowdy Baby", "Dhanush", "Mass", "excited", "Tamil", 9.0, 10, _yt("Rowdy Baby Dhanush official audio")),
    # ── Expanded v2 Songs ────────────────────────────────────────
    # Sad — more Telugu/Hindi/English
    ("Vellipomaakey", "AR Rahman", "Melody", "sad", "Telugu", 8.6, 8, _yt("Vellipomaakey AR Rahman official audio")),
    ("Naa Manasuni Thake", "Sid Sriram", "Melody", "sad", "Telugu", 8.4, 8, _yt("Naa Manasuni Thake Sid Sriram official audio")),
    ("Pranamam", "Haricharan", "Melody", "sad", "Telugu", 8.2, 7, _yt("Pranamam Haricharan official audio")),
    ("Nee Neeli Kannullona", "Vijay Deverakonda", "Melody", "sad", "Telugu", 8.0, 7, _yt("Nee Neeli Kannullona Dear Comrade official audio")),
    ("Ae Dil Hai Mushkil", "Arijit Singh", "Bollywood", "sad", "Hindi", 8.6, 9, _yt("Ae Dil Hai Mushkil Arijit Singh official audio")),
    ("Hamari Adhuri Kahani", "Arijit Singh", "Bollywood", "sad", "Hindi", 8.3, 8, _yt("Hamari Adhuri Kahani Arijit Singh official audio")),
    ("Bekhayali", "Sachet Tandon", "Bollywood", "sad", "Hindi", 8.7, 9, _yt("Bekhayali Sachet Tandon official audio")),
    ("Hurt", "Johnny Cash", "Country", "sad", "English", 8.9, 9, _yt("Hurt Johnny Cash official audio")),
    ("Skinny Love", "Bon Iver", "Indie Folk", "sad", "English", 8.4, 8, _yt("Skinny Love Bon Iver official audio")),
    ("Mad World", "Gary Jules", "Indie", "sad", "English", 8.6, 8, _yt("Mad World Gary Jules official audio")),
    # Stressed — more Telugu/Hindi/English
    ("Khalasi", "Aditya Gadhvi", "Folk Fusion", "stressed", "Hindi", 8.5, 9, _yt("Khalasi Aditya Gadhvi official audio")),
    ("Teri Mitti", "B Praak", "Bollywood", "stressed", "Hindi", 8.7, 9, _yt("Teri Mitti B Praak official audio")),
    ("O Saathi", "Atif Aslam", "Bollywood", "stressed", "Hindi", 8.0, 7, _yt("O Saathi Atif Aslam official audio")),
    ("Nuvvu Leka Nenu Lenu", "SPB", "Melody", "stressed", "Telugu", 8.2, 7, _yt("Nuvvu Leka Nenu Lenu SPB official audio")),
    ("Manasantha Nuvve Title", "Udit Narayan", "Melody", "stressed", "Telugu", 8.0, 7, _yt("Manasantha Nuvve Title Udit Narayan official audio")),
    ("The Sound of Silence", "Simon & Garfunkel", "Folk", "stressed", "English", 9.0, 9, _yt("The Sound of Silence Simon Garfunkel official audio")),
    ("Creep", "Radiohead", "Alternative", "stressed", "English", 8.8, 9, _yt("Creep Radiohead official audio")),
    ("Yesterday", "The Beatles", "Rock", "stressed", "English", 9.1, 10, _yt("Yesterday The Beatles official audio")),
    # Calm — more variety
    ("Kya Mujhe Pyaar Hai", "KK", "Bollywood", "calm", "Hindi", 8.4, 8, _yt("Kya Mujhe Pyaar Hai KK official audio")),
    ("Pal", "Arijit Singh", "Bollywood", "calm", "Hindi", 8.2, 7, _yt("Pal Arijit Singh official audio")),
    ("Lukka Chuppi", "AR Rahman", "Bollywood", "calm", "Hindi", 8.5, 8, _yt("Lukka Chuppi AR Rahman official audio")),
    ("Mellaga Tellarindoi", "Unni Menon", "Melody", "calm", "Telugu", 8.3, 7, _yt("Mellaga Tellarindoi Unni Menon official audio")),
    ("Chandamama", "SPB", "Classic", "calm", "Telugu", 8.4, 7, _yt("Chandamama SPB official audio")),
    ("Somewhere Only We Know", "Keane", "Alternative", "calm", "English", 8.5, 8, _yt("Somewhere Only We Know Keane official audio")),
    ("Yellow", "Coldplay", "Alternative", "calm", "English", 8.8, 9, _yt("Yellow Coldplay official audio")),
    # Neutral — more diversity
    ("Kahani Suno", "Kaifi Khalil", "Indie", "neutral", "Hindi", 8.0, 8, _yt("Kahani Suno Kaifi Khalil official audio")),
    ("Tera Ban Jaunga", "Akhil Sachdeva", "Bollywood", "neutral", "Hindi", 8.1, 7, _yt("Tera Ban Jaunga Akhil Sachdeva official audio")),
    ("Oh Sita Hey Rama", "Anurag Kulkarni", "Melody", "neutral", "Telugu", 8.3, 8, _yt("Oh Sita Hey Rama Anurag Kulkarni official audio")),
    ("Saranga Dariya", "Mangli", "Folk", "neutral", "Telugu", 8.5, 8, _yt("Saranga Dariya Mangli official audio")),
    ("Clocks", "Coldplay", "Alternative", "neutral", "English", 8.7, 9, _yt("Clocks Coldplay official audio")),
    ("Viva La Vida", "Coldplay", "Alternative", "neutral", "English", 8.8, 9, _yt("Viva La Vida Coldplay official audio")),
    # Angry — more Hindi/English
    ("Tadap Tadap", "KK", "Bollywood", "angry", "Hindi", 8.5, 8, _yt("Tadap Tadap KK official audio")),
    ("Chingari Koi Bhadke", "Kishore Kumar", "Classic", "angry", "Hindi", 8.3, 7, _yt("Chingari Koi Bhadke Kishore Kumar official audio")),
    ("Killing in the Name", "Rage Against the Machine", "Metal", "angry", "English", 8.9, 9, _yt("Killing in the Name Rage Against the Machine official audio")),
    ("Given Up", "Linkin Park", "Nu Metal", "angry", "English", 8.5, 8, _yt("Given Up Linkin Park official audio")),
    # Motivational — more Hindi/English
    ("Apna Time Aayega", "Ranveer Singh", "Hip Hop", "motivational", "Hindi", 8.5, 9, _yt("Apna Time Aayega Ranveer Singh official audio")),
    ("Sultan Title", "Sukhwinder Singh", "Bollywood", "motivational", "Hindi", 8.3, 8, _yt("Sultan Title Sukhwinder Singh official audio")),
    ("We Will Rock You", "Queen", "Rock", "motivational", "English", 9.0, 10, _yt("We Will Rock You Queen official audio")),
    ("Believer", "Imagine Dragons", "Alternative", "motivational", "English", 8.8, 9, _yt("Believer Imagine Dragons official audio")),
    # Energetic — more diversity
    ("Shankara", "Anurag Kulkarni", "Mass", "energetic", "Telugu", 8.0, 7, _yt("Shankara Anurag Kulkarni official audio")),
    ("Jai Ho", "AR Rahman", "Bollywood", "energetic", "Hindi", 8.8, 9, _yt("Jai Ho AR Rahman official audio")),
    ("Swag Se Swagat", "Vishal Dadlani", "Bollywood", "energetic", "Hindi", 8.2, 8, _yt("Swag Se Swagat Vishal Dadlani official audio")),
    ("Pump It", "Black Eyed Peas", "Hip Hop", "energetic", "English", 8.3, 8, _yt("Pump It Black Eyed Peas official audio")),
    # Romantic — more Hindi/English
    ("Hawayein", "Arijit Singh", "Bollywood", "romantic", "Hindi", 8.6, 9, _yt("Hawayein Arijit Singh official audio")),
    ("Dil Diyan Gallan", "Atif Aslam", "Bollywood", "romantic", "Hindi", 8.7, 9, _yt("Dil Diyan Gallan Atif Aslam official audio")),
    ("Just the Way You Are", "Bruno Mars", "Pop", "romantic", "English", 8.5, 9, _yt("Just the Way You Are Bruno Mars official audio")),
    ("Make You Feel My Love", "Adele", "Pop", "romantic", "English", 8.8, 9, _yt("Make You Feel My Love Adele official audio")),
]

MOVIES = [
    ("Ala Vaikunthapurramuloo", "Family Drama", 2020, "happy", "Telugu", 8.5, 9, "Netflix", _yt("Ala Vaikunthapurramuloo Telugu official trailer")),
    ("F2: Fun and Frustration", "Comedy", 2019, "happy", "Telugu", 7.8, 8, "Amazon Prime", _yt("F2: Fun and Frustration Telugu official trailer")),
    ("Jaathi Ratnalu", "Comedy", 2021, "happy", "Telugu", 8.0, 8, "Amazon Prime", _yt("Jaathi Ratnalu Telugu official trailer")),
    ("Bheeshma", "Romantic Comedy", 2020, "happy", "Telugu", 7.9, 8, "Netflix", _yt("Bheeshma Telugu official trailer")),
    ("Shatamanam Bhavati", "Family Drama", 2017, "happy", "Telugu", 7.5, 7, "Hotstar", _yt("Shatamanam Bhavati Telugu official trailer")),
    ("DJ: Duvvada Jagannadham", "Action Comedy", 2017, "happy", "Telugu", 7.3, 7, "Netflix", _yt("DJ: Duvvada Jagannadham Telugu official trailer")),
    ("S/O Satyamurthy", "Family Drama", 2015, "happy", "Telugu", 7.6, 7, "Hotstar", _yt("S/O Satyamurthy Telugu official trailer")),
    ("A Aa", "Romantic Comedy", 2016, "happy", "Telugu", 7.8, 8, "Netflix", _yt("A Aa Telugu official trailer")),
    ("Geetha Govindam", "Romantic Comedy", 2018, "happy", "Telugu", 8.2, 9, "Amazon Prime", _yt("Geetha Govindam Telugu official trailer")),
    ("MCA", "Comedy Drama", 2017, "happy", "Telugu", 7.5, 7, "Hotstar", _yt("MCA Telugu official trailer")),
    ("3 Idiots", "Comedy Drama", 2009, "happy", "Hindi", 9.0, 10, "Netflix", _yt("3 Idiots Hindi official trailer")),
    ("Zindagi Na Milegi Dobara", "Drama", 2011, "happy", "Hindi", 8.5, 9, "Amazon Prime", _yt("Zindagi Na Milegi Dobara Hindi official trailer")),
    ("Queen", "Comedy Drama", 2013, "happy", "Hindi", 8.2, 8, "Netflix", _yt("Queen Hindi official trailer")),
    ("Hera Pheri", "Comedy", 2000, "happy", "Hindi", 8.7, 9, "Amazon Prime", _yt("Hera Pheri Hindi official trailer")),
    ("Inside Out", "Animation", 2015, "happy", "English", 8.2, 9, "Disney+ Hotstar", _yt("Inside Out English official trailer")),
    ("The Intouchables", "Comedy Drama", 2011, "happy", "English", 8.5, 9, "Amazon Prime", _yt("The Intouchables English official trailer")),
    ("Forrest Gump", "Drama", 1994, "happy", "English", 8.8, 10, "Amazon Prime", _yt("Forrest Gump English official trailer")),
    ("Ratatouille", "Animation", 2007, "happy", "English", 8.0, 8, "Disney+ Hotstar", _yt("Ratatouille English official trailer")),
    ("Nanban", "Comedy Drama", 2012, "happy", "Tamil", 8.0, 8, "Amazon Prime", _yt("Nanban Tamil official trailer")),
    ("Varuthapadatha Valibar", "Comedy", 2013, "happy", "Tamil", 7.5, 7, "Hotstar", _yt("Varuthapadatha Valibar Tamil official trailer")),
    ("Majili", "Love Drama", 2019, "sad", "Telugu", 8.2, 8, "Hotstar", _yt("Majili Telugu official trailer")),
    ("Ye Maaya Chesave", "Romance", 2010, "sad", "Telugu", 8.5, 9, "Amazon Prime", _yt("Ye Maaya Chesave Telugu official trailer")),
    ("Nuvvostanante Nenoddantana", "Romance", 2005, "sad", "Telugu", 8.0, 8, "Netflix", _yt("Nuvvostanante Nenoddantana Telugu official trailer")),
    ("96 Telugu", "Romance", 2019, "sad", "Telugu", 8.3, 8, "Amazon Prime", _yt("96 Telugu Telugu official trailer")),
    ("Fidaa", "Romance Drama", 2017, "sad", "Telugu", 8.0, 8, "Netflix", _yt("Fidaa Telugu official trailer")),
    ("Jersey", "Sports Drama", 2019, "sad", "Telugu", 8.5, 9, "Netflix", _yt("Jersey Telugu official trailer")),
    ("Dear Comrade", "Romance", 2019, "sad", "Telugu", 7.8, 7, "Netflix", _yt("Dear Comrade Telugu official trailer")),
    ("Kabir Singh", "Love Drama", 2019, "sad", "Hindi", 7.5, 9, "Netflix", _yt("Kabir Singh Hindi official trailer")),
    ("Lootera", "Period Romance", 2013, "sad", "Hindi", 7.8, 7, "Hotstar", _yt("Lootera Hindi official trailer")),
    ("Rockstar", "Musical Drama", 2011, "sad", "Hindi", 8.0, 8, "Netflix", _yt("Rockstar Hindi official trailer")),
    ("The Fault in Our Stars", "Romance", 2014, "sad", "English", 7.7, 8, "Disney+ Hotstar", _yt("The Fault in Our Stars English official trailer")),
    ("A Walk to Remember", "Romance", 2002, "sad", "English", 7.4, 7, "Amazon Prime", _yt("A Walk to Remember English official trailer")),
    ("The Notebook", "Romance", 2004, "sad", "English", 7.8, 9, "Netflix", _yt("The Notebook English official trailer")),
    ("96", "Romance", 2018, "sad", "Tamil", 8.5, 9, "Amazon Prime", _yt("96 Tamil official trailer")),
    ("Vinnaithaandi Varuvaayaa", "Romance", 2010, "sad", "Tamil", 8.3, 8, "Netflix", _yt("Vinnaithaandi Varuvaayaa Tamil official trailer")),
    ("Arjun Reddy", "Romance Drama", 2017, "romantic", "Telugu", 8.5, 10, "Netflix", _yt("Arjun Reddy Telugu official trailer")),
    ("Bommarillu", "Romantic Comedy", 2006, "romantic", "Telugu", 8.3, 9, "Amazon Prime", _yt("Bommarillu Telugu official trailer")),
    ("Fidaa", "Romance", 2017, "romantic", "Telugu", 8.0, 8, "Netflix", _yt("Fidaa Telugu official trailer")),
    ("Mr. Perfect", "Romance", 2011, "romantic", "Telugu", 7.5, 7, "Hotstar", _yt("Mr. Perfect Telugu official trailer")),
    ("Nuvvu Nenu", "Romantic Comedy", 2001, "romantic", "Telugu", 8.0, 8, "Netflix", _yt("Nuvvu Nenu Telugu official trailer")),
    ("Srirastu Shubhamastu", "Romance", 2016, "romantic", "Telugu", 7.3, 7, "Amazon Prime", _yt("Srirastu Shubhamastu Telugu official trailer")),
    ("Premam", "Love Drama", 2016, "romantic", "Telugu", 8.2, 8, "Hotstar", _yt("Premam Telugu official trailer")),
    ("Geetha Govindam", "Romantic Comedy", 2018, "romantic", "Telugu", 8.2, 9, "Amazon Prime", _yt("Geetha Govindam Telugu official trailer")),
    ("Ninnu Kori", "Romance Drama", 2017, "romantic", "Telugu", 8.0, 8, "Netflix", _yt("Ninnu Kori Telugu official trailer")),
    ("Sita Ramam", "Period Romance", 2022, "romantic", "Telugu", 8.8, 10, "Amazon Prime", _yt("Sita Ramam Telugu official trailer")),
    ("Dilwale Dulhania Le Jayenge", "Romance", 1995, "romantic", "Hindi", 8.8, 10, "Amazon Prime", _yt("Dilwale Dulhania Le Jayenge Hindi official trailer")),
    ("Jab We Met", "Romantic Comedy", 2007, "romantic", "Hindi", 8.2, 9, "Netflix", _yt("Jab We Met Hindi official trailer")),
    ("Raanjhanaa", "Romance", 2013, "romantic", "Hindi", 7.5, 7, "Hotstar", _yt("Raanjhanaa Hindi official trailer")),
    ("La La Land", "Musical Romance", 2016, "romantic", "English", 8.0, 9, "Netflix", _yt("La La Land English official trailer")),
    ("The Proposal", "Romantic Comedy", 2009, "romantic", "English", 7.0, 7, "Disney+ Hotstar", _yt("The Proposal English official trailer")),
    ("OK Kanmani", "Romance", 2015, "romantic", "Tamil", 8.0, 8, "Hotstar", _yt("OK Kanmani Tamil official trailer")),
    ("Premam Tamil", "Romance", 2015, "romantic", "Tamil", 8.2, 8, "Netflix", _yt("Premam Tamil Tamil official trailer")),
    ("RRR", "Action Epic", 2022, "energetic", "Telugu", 8.8, 10, "Netflix", _yt("RRR Telugu official trailer")),
    ("Baahubali: The Beginning", "Epic Action", 2015, "energetic", "Telugu", 8.5, 10, "Hotstar", _yt("Baahubali: The Beginning Telugu official trailer")),
    ("Baahubali 2", "Epic Action", 2017, "energetic", "Telugu", 8.6, 10, "Hotstar", _yt("Baahubali 2 Telugu official trailer")),
    ("Pushpa", "Action Drama", 2021, "energetic", "Telugu", 8.0, 9, "Amazon Prime", _yt("Pushpa Telugu official trailer")),
    ("Sarileru Neekevvaru", "Action Comedy", 2020, "energetic", "Telugu", 7.5, 8, "Hotstar", _yt("Sarileru Neekevvaru Telugu official trailer")),
    ("Akhanda", "Action", 2021, "energetic", "Telugu", 7.8, 8, "Hotstar", _yt("Akhanda Telugu official trailer")),
    ("Bheemla Nayak", "Action", 2022, "energetic", "Telugu", 7.6, 8, "Hotstar", _yt("Bheemla Nayak Telugu official trailer")),
    ("Sye", "Sports Drama", 2004, "energetic", "Telugu", 8.0, 8, "Amazon Prime", _yt("Sye Telugu official trailer")),
    ("War", "Action", 2019, "energetic", "Hindi", 7.5, 8, "Amazon Prime", _yt("War Hindi official trailer")),
    ("Dhoom 3", "Action", 2013, "energetic", "Hindi", 7.0, 8, "Netflix", _yt("Dhoom 3 Hindi official trailer")),
    ("Mad Max: Fury Road", "Action", 2015, "energetic", "English", 8.1, 9, "Amazon Prime", _yt("Mad Max: Fury Road English official trailer")),
    ("Top Gun: Maverick", "Action", 2022, "energetic", "English", 8.3, 10, "Amazon Prime", _yt("Top Gun: Maverick English official trailer")),
    ("Vikram", "Action Thriller", 2022, "energetic", "Tamil", 8.4, 9, "Disney+ Hotstar", _yt("Vikram Tamil official trailer")),
    ("Master", "Action Drama", 2021, "energetic", "Tamil", 7.5, 8, "Amazon Prime", _yt("Master Tamil official trailer")),
    ("Sarileru Neekevvaru", "Military Drama", 2020, "motivational", "Telugu", 7.5, 8, "Hotstar", _yt("Sarileru Neekevvaru Telugu official trailer")),
    ("Vakeel Saab", "Legal Drama", 2021, "motivational", "Telugu", 7.3, 7, "Amazon Prime", _yt("Vakeel Saab Telugu official trailer")),
    ("Leader", "Political Drama", 2010, "motivational", "Telugu", 8.0, 8, "Netflix", _yt("Leader Telugu official trailer")),
    ("Nannaku Prematho", "Drama", 2016, "motivational", "Telugu", 8.2, 8, "Netflix", _yt("Nannaku Prematho Telugu official trailer")),
    ("Maharshi", "Social Drama", 2019, "motivational", "Telugu", 7.5, 8, "Amazon Prime", _yt("Maharshi Telugu official trailer")),
    ("Srimanthudu", "Social Drama", 2015, "motivational", "Telugu", 7.8, 8, "Netflix", _yt("Srimanthudu Telugu official trailer")),
    ("Super 30", "Biographical", 2019, "motivational", "Hindi", 7.5, 7, "Hotstar", _yt("Super 30 Hindi official trailer")),
    ("Dangal", "Sports Drama", 2016, "motivational", "Hindi", 8.8, 10, "Netflix", _yt("Dangal Hindi official trailer")),
    ("Bhaag Milkha Bhaag", "Sports Drama", 2013, "motivational", "Hindi", 8.2, 9, "Amazon Prime", _yt("Bhaag Milkha Bhaag Hindi official trailer")),
    ("The Pursuit of Happyness", "Drama", 2006, "motivational", "English", 8.0, 9, "Netflix", _yt("The Pursuit of Happyness English official trailer")),
    ("Rocky", "Sports Drama", 1976, "motivational", "English", 8.1, 9, "Amazon Prime", _yt("Rocky English official trailer")),
    ("Bigil", "Sports Drama", 2019, "motivational", "Tamil", 7.5, 8, "Hotstar", _yt("Bigil Tamil official trailer")),
    ("Bommarillu", "Family Drama", 2006, "calm", "Telugu", 8.3, 9, "Amazon Prime", _yt("Bommarillu Telugu official trailer")),
    ("Shatamanam Bhavati", "Family Drama", 2017, "calm", "Telugu", 7.5, 7, "Hotstar", _yt("Shatamanam Bhavati Telugu official trailer")),
    ("Chi La Sow", "Slice of Life", 2018, "calm", "Telugu", 7.8, 7, "Netflix", _yt("Chi La Sow Telugu official trailer")),
    ("Mallesham", "Biographical", 2019, "calm", "Telugu", 8.0, 7, "Amazon Prime", _yt("Mallesham Telugu official trailer")),
    ("Care of Kancharapalem", "Indie", 2018, "calm", "Telugu", 8.5, 8, "Netflix", _yt("Care of Kancharapalem Telugu official trailer")),
    ("Life of Pi", "Adventure", 2012, "calm", "English", 8.0, 9, "Disney+ Hotstar", _yt("Life of Pi English official trailer")),
    ("The Secret Life of Walter Mitty", "Adventure", 2013, "calm", "English", 7.3, 7, "Amazon Prime", _yt("The Secret Life of Walter Mitty English official trailer")),
    ("PK", "Comedy Drama", 2014, "calm", "Hindi", 8.0, 9, "Netflix", _yt("PK Hindi official trailer")),
    ("Oh My Kadavule", "Fantasy", 2020, "calm", "Tamil", 7.8, 7, "Hotstar", _yt("Oh My Kadavule Tamil official trailer")),
    ("Temper", "Action", 2015, "angry", "Telugu", 7.8, 8, "Netflix", _yt("Temper Telugu official trailer")),
    ("Gabbar Singh", "Action Comedy", 2012, "angry", "Telugu", 8.2, 9, "Netflix", _yt("Gabbar Singh Telugu official trailer")),
    ("Attarintiki Daredi", "Action Drama", 2013, "angry", "Telugu", 7.8, 8, "Hotstar", _yt("Attarintiki Daredi Telugu official trailer")),
    ("Srimanthudu", "Action Drama", 2015, "angry", "Telugu", 7.8, 8, "Netflix", _yt("Srimanthudu Telugu official trailer")),
    ("Dookudu", "Action", 2011, "angry", "Telugu", 8.0, 8, "Netflix", _yt("Dookudu Telugu official trailer")),
    ("Ghajini", "Action Thriller", 2008, "angry", "Hindi", 7.5, 8, "Netflix", _yt("Ghajini Hindi official trailer")),
    ("Singham", "Action", 2011, "angry", "Hindi", 7.3, 8, "Amazon Prime", _yt("Singham Hindi official trailer")),
    ("John Wick", "Action Thriller", 2014, "angry", "English", 7.4, 9, "Amazon Prime", _yt("John Wick English official trailer")),
    ("Gladiator", "Action Epic", 2000, "angry", "English", 8.5, 10, "Amazon Prime", _yt("Gladiator English official trailer")),
    ("Kaithi", "Action Thriller", 2019, "angry", "Tamil", 8.5, 9, "Hotstar", _yt("Kaithi Tamil official trailer")),
    ("Mahanati", "Biographical", 2018, "neutral", "Telugu", 8.5, 9, "Amazon Prime", _yt("Mahanati Telugu official trailer")),
    ("Agent Sai Srinivasa Athreya", "Mystery Comedy", 2019, "neutral", "Telugu", 8.0, 8, "Aha", _yt("Agent Sai Srinivasa Athreya Telugu official trailer")),
    ("HIT", "Thriller", 2020, "neutral", "Telugu", 7.8, 7, "Amazon Prime", _yt("HIT Telugu official trailer")),
    ("Evaru", "Thriller", 2019, "neutral", "Telugu", 8.0, 8, "Netflix", _yt("Evaru Telugu official trailer")),
    ("Inception", "Sci-Fi", 2010, "neutral", "English", 8.8, 10, "Netflix", _yt("Inception English official trailer")),
    ("Interstellar", "Sci-Fi", 2014, "neutral", "English", 8.6, 10, "Amazon Prime", _yt("Interstellar English official trailer")),
    ("The Shawshank Redemption", "Drama", 1994, "neutral", "English", 9.3, 10, "Netflix", _yt("The Shawshank Redemption English official trailer")),
    ("Andhadhun", "Thriller", 2018, "neutral", "Hindi", 8.5, 9, "Netflix", _yt("Andhadhun Hindi official trailer")),
    ("Vikram Vedha", "Thriller", 2017, "neutral", "Tamil", 8.3, 8, "Amazon Prime", _yt("Vikram Vedha Tamil official trailer")),
    ("Anthahpuram", "Thriller", 2022, "stressed", "Telugu", 7.3, 6, "Aha", _yt("Anthahpuram Telugu official trailer")),
    ("Rakshasudu", "Thriller", 2019, "stressed", "Telugu", 8.0, 8, "Netflix", _yt("Rakshasudu Telugu official trailer")),
    ("Kshanam", "Thriller", 2016, "stressed", "Telugu", 8.2, 8, "Amazon Prime", _yt("Kshanam Telugu official trailer")),
    ("Goodachari", "Spy Thriller", 2018, "stressed", "Telugu", 8.0, 8, "Amazon Prime", _yt("Goodachari Telugu official trailer")),
    ("Get Out", "Horror Thriller", 2017, "stressed", "English", 7.7, 8, "Netflix", _yt("Get Out English official trailer")),
    ("Black Swan", "Psychological", 2010, "stressed", "English", 8.0, 8, "Disney+ Hotstar", _yt("Black Swan English official trailer")),
    ("Talaash", "Mystery", 2012, "stressed", "Hindi", 7.5, 7, "Netflix", _yt("Talaash Hindi official trailer")),
    ("Psycho", "Thriller", 2020, "stressed", "Tamil", 7.3, 7, "Netflix", _yt("Psycho Tamil official trailer")),
    ("Race Gurram", "Action Comedy", 2014, "excited", "Telugu", 7.8, 8, "Hotstar", _yt("Race Gurram Telugu official trailer")),
    ("Julayi", "Action Comedy", 2012, "excited", "Telugu", 8.0, 8, "Netflix", _yt("Julayi Telugu official trailer")),
    ("Pokiri", "Action Thriller", 2006, "excited", "Telugu", 8.5, 9, "Netflix", _yt("Pokiri Telugu official trailer")),
    ("Athadu", "Action", 2005, "excited", "Telugu", 8.0, 8, "Hotstar", _yt("Athadu Telugu official trailer")),
    ("Khaleja", "Action Comedy", 2010, "excited", "Telugu", 7.5, 7, "Netflix", _yt("Khaleja Telugu official trailer")),
    ("Avengers: Endgame", "Superhero", 2019, "excited", "English", 8.4, 10, "Disney+ Hotstar", _yt("Avengers: Endgame English official trailer")),
    ("Spider-Man: No Way Home", "Superhero", 2021, "excited", "English", 8.3, 10, "Netflix", _yt("Spider-Man: No Way Home English official trailer")),
    ("Dhoom 2", "Action", 2006, "excited", "Hindi", 7.0, 8, "Netflix", _yt("Dhoom 2 Hindi official trailer")),
    ("Thuppakki", "Action", 2012, "excited", "Tamil", 8.0, 8, "Amazon Prime", _yt("Thuppakki Tamil official trailer")),
    # ── Expanded v2 Movies ───────────────────────────────────────
    # Sad — more variety
    ("Devadas", "Drama", 2002, "sad", "Hindi", 7.5, 8, "Netflix", _yt("Devadas Hindi official trailer")),
    ("Aashiqui 2", "Musical Romance", 2013, "sad", "Hindi", 7.8, 9, "Hotstar", _yt("Aashiqui 2 Hindi official trailer")),
    ("Blue Valentine", "Romance", 2010, "sad", "English", 7.4, 7, "Amazon Prime", _yt("Blue Valentine English official trailer")),
    ("Manchester by the Sea", "Drama", 2016, "sad", "English", 7.8, 8, "Amazon Prime", _yt("Manchester by the Sea English official trailer")),
    ("Arjun Reddy", "Romance Drama", 2017, "sad", "Telugu", 8.5, 10, "Netflix", _yt("Arjun Reddy Telugu official trailer")),
    ("Nuvvostanante Nenoddantana", "Romance", 2005, "sad", "Telugu", 8.0, 8, "Amazon Prime", _yt("Nuvvostanante Nenoddantana sad official trailer")),
    # Stressed — more variety
    ("Shutter Island", "Psychological", 2010, "stressed", "English", 8.2, 9, "Netflix", _yt("Shutter Island English official trailer")),
    ("Raazi", "Spy Thriller", 2018, "stressed", "Hindi", 7.8, 8, "Amazon Prime", _yt("Raazi Hindi official trailer")),
    ("Kahaani", "Thriller", 2012, "stressed", "Hindi", 8.1, 8, "Netflix", _yt("Kahaani Hindi official trailer")),
    ("Karthikeya 2", "Mystery Thriller", 2022, "stressed", "Telugu", 7.8, 8, "Aha", _yt("Karthikeya 2 Telugu official trailer")),
    # Calm — more variety
    ("Midnight in Paris", "Fantasy Drama", 2011, "calm", "English", 7.7, 8, "Amazon Prime", _yt("Midnight in Paris English official trailer")),
    ("Piku", "Comedy Drama", 2015, "calm", "Hindi", 7.6, 8, "Netflix", _yt("Piku Hindi official trailer")),
    ("English Vinglish", "Comedy Drama", 2012, "calm", "Hindi", 7.8, 8, "Hotstar", _yt("English Vinglish Hindi official trailer")),
    ("Middle Class Melodies", "Slice of Life", 2020, "calm", "Telugu", 7.5, 7, "Amazon Prime", _yt("Middle Class Melodies Telugu official trailer")),
    # Happy — more
    ("Coco", "Animation", 2017, "happy", "English", 8.4, 9, "Disney+ Hotstar", _yt("Coco English official trailer")),
    ("Munna Bhai MBBS", "Comedy", 2003, "happy", "Hindi", 8.3, 9, "Netflix", _yt("Munna Bhai MBBS Hindi official trailer")),
    ("Shubh Mangal Zyada Saavdhan", "Comedy", 2020, "happy", "Hindi", 6.5, 7, "Amazon Prime", _yt("Shubh Mangal Zyada Saavdhan Hindi official trailer")),
    ("Oh Baby", "Fantasy Comedy", 2019, "happy", "Telugu", 8.0, 8, "Netflix", _yt("Oh Baby Telugu official trailer")),
    # Motivational — more
    ("Rang De Basanti", "Social Drama", 2006, "motivational", "Hindi", 8.2, 9, "Netflix", _yt("Rang De Basanti Hindi official trailer")),
    ("Whiplash", "Drama", 2014, "motivational", "English", 8.5, 9, "Amazon Prime", _yt("Whiplash English official trailer")),
    ("Coach Carter", "Sports Drama", 2005, "motivational", "English", 7.5, 8, "Netflix", _yt("Coach Carter English official trailer")),
    # Angry — more
    ("KGF Chapter 2", "Action", 2022, "angry", "Hindi", 8.0, 10, "Amazon Prime", _yt("KGF Chapter 2 Hindi official trailer")),
    ("The Dark Knight", "Action Thriller", 2008, "angry", "English", 9.0, 10, "Netflix", _yt("The Dark Knight English official trailer")),
    ("Chatrapathi", "Action", 2005, "angry", "Telugu", 8.2, 8, "Amazon Prime", _yt("Chatrapathi Telugu official trailer")),
    # Excited — more
    ("Dangal", "Sports", 2016, "excited", "Hindi", 8.8, 10, "Netflix", _yt("Dangal excited Hindi official trailer")),
    ("The Avengers", "Superhero", 2012, "excited", "English", 8.0, 10, "Disney+ Hotstar", _yt("The Avengers English official trailer")),
    ("Waltair Veerayya", "Action Comedy", 2023, "excited", "Telugu", 7.5, 8, "Netflix", _yt("Waltair Veerayya Telugu official trailer")),
]


def seed_database():
    init_db()
    conn = get_connection()
    count = conn.execute("SELECT COUNT(*) FROM songs").fetchone()[0]
    if count > 0:
        print("Database already seeded. Skipping.")
        conn.close()
        return
    for s in SONGS:
        conn.execute(
            "INSERT INTO songs (title, artist, genre, mood_tag, language, rating, popularity, youtube_url) VALUES (?,?,?,?,?,?,?,?)", s
        )
    for m in MOVIES:
        conn.execute(
            "INSERT INTO movies (title, genre, year, mood_tag, language, rating, popularity, ott_platform, ott_url) VALUES (?,?,?,?,?,?,?,?,?)", m
        )
    conn.commit()
    conn.close()
    print(f"✅ Seeded {len(SONGS)} songs and {len(MOVIES)} movies.")

if __name__ == "__main__":
    seed_database()
